/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Login (void);
GtkWidget* create_AdminDashboard (void);
GtkWidget* create_MemberDashboard (void);
GtkWidget* create_MemberManage (void);
GtkWidget* create_Mycoach (void);
GtkWidget* create_addmember (void);
GtkWidget* create_recherchemember (void);
GtkWidget* create_deletemember (void);
GtkWidget* create_restoremember (void);
GtkWidget* create_reqcoach (void);
GtkWidget* create_Statsview (void);
GtkWidget* create_apiFoodStats (void);
GtkWidget* create_ww1 (void);
GtkWidget* create_ww2 (void);
GtkWidget* create_ww3 (void);
GtkWidget* create_ww5 (void);
GtkWidget* create_ww6 (void);
GtkWidget* create_CourseManag (void);
GtkWidget* create_ew_addcourse (void);
GtkWidget* create_ewrecherchecours (void);
GtkWidget* create_ewdeletecous (void);
GtkWidget* create_ewrestorecours (void);
GtkWidget* create_ewstats (void);
