/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Login (void);
GtkWidget* create_AdminDashboard (void);
GtkWidget* create_MemberDashboard (void);
GtkWidget* create_MemberManage (void);
GtkWidget* create_Mycoach (void);
GtkWidget* create_addmember (void);
GtkWidget* create_recherchemember (void);
GtkWidget* create_deletemember (void);
GtkWidget* create_restoremember (void);
GtkWidget* create_reqcoach (void);
GtkWidget* create_Statsview (void);
GtkWidget* create_apiFoodStats (void);
GtkWidget* create_ww1 (void);
GtkWidget* create_ww2 (void);
GtkWidget* create_ww3 (void);
GtkWidget* create_ww5 (void);
GtkWidget* create_ww6 (void);
GtkWidget* create_CourseManag (void);
GtkWidget* create_ew_addcourse (void);
GtkWidget* create_ewrecherchecours (void);
GtkWidget* create_ewdeletecous (void);
GtkWidget* create_ewrestorecours (void);
GtkWidget* create_ewstats (void);

GtkWidget* create_CoachManagAdmin (void);
GtkWidget* create_addCoachAdmin (void);
GtkWidget* create_rechercheCoach (void);
GtkWidget* create_deleteCoach (void);
GtkWidget* create_restoreCoach (void);
GtkWidget* create_EventManagAdmin (void);
GtkWidget* create_addEvent (void);
GtkWidget* create_rechercheEvent (void);
GtkWidget* create_deleteEvent (void);
GtkWidget* create_restoreEvent (void);
GtkWidget* create_addEquipAdmin (void);
GtkWidget* create_rechercherEquip (void);
GtkWidget* create_deleteEquip (void);
GtkWidget* create_resotreEquip (void);
GtkWidget* create_EquipManagAdmin (void);
