/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Login;
  GtkWidget *AdminDashboard;
  GtkWidget *MemberDashboard;


#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  /* FIX: Add multiple pixmaps directories */
  add_pixmap_directory ("pixmaps");  // Current directory
  add_pixmap_directory ("../pixmaps");  // Parent directory
  add_pixmap_directory ("/home/ali/Projects/PROJET/pourvalider/PROJET/pixmaps");  // Absolute path
  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");  // System path

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Login = create_Login ();
  gtk_widget_show (Login);
  /*AdminDashboard = create_AdminDashboard ();
  gtk_widget_show (AdminDashboard);
  MemberDashboard = create_MemberDashboard ();
  gtk_widget_show (MemberDashboard);
  MemberManage = create_MemberManage ();
  gtk_widget_show (MemberManage);
  Mycoach = create_Mycoach ();
  gtk_widget_show (Mycoach);
  addmember = create_addmember ();
  gtk_widget_show (addmember);
  recherchemember = create_recherchemember ();
  gtk_widget_show (recherchemember);
  modifymember = create_modifymember ();
  gtk_widget_show (modifymember);
  deletemember = create_deletemember ();
  gtk_widget_show (deletemember);
  restoremember = create_restoremember ();
  gtk_widget_show (restoremember);
  reqcoach = create_reqcoach ();
  gtk_widget_show (reqcoach);*/

  gtk_main ();
  return 0;
}

